###GET CURRENTLY LOGED IN USER
GET http://localhost:3000/auth/whoami


### Sign out
POST http://localhost:3000/auth/signout
###CREATE USER
POST https://git.heroku.com/stormy-falls-62014.git/auth/signup
content-Type: application/json

{
"email":"khodzapro@gmail.com",
"password":"2003qwerty" 
}
 

###SIGN IN USER
POST http://localhost:3000/auth/signin
content-Type: application/json

{
"email":"khodzapro@gmail.com",
"password":"2003qwerty" 
}
 
###GET USER BY ID
GET http://localhost:3000/auth/2

###GET USERS BY EMAIL
GET http://localhost:3000/auth?email=khodzapro@gmail.com

###UPDATE USER 

PATCH http://localhost:3000/auth/231341
content-Type: application/json

{
    "email":"prostrel4ik@gmail.com"
}

###DELETE USER

DELETE http://localhost:3000/auth/3